[versions]
kotlin = "2.1.20"
fabric-loom = "1.16-SNAPSHOT"
iridium = "3.5.0"

fzzy_config = "0.7.6+1.21.11"
modmenu = "17.0.0"

[libraries]
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fzzy-config = { module = "me.fzzyhmstrs:fzzy_config", version.ref = "fzzy_config" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }
